import type { DiscourseTopic, DiscourseTopicDetail } from './types'

export const MOCK_TOPICS: DiscourseTopic[] = [
  {
    id: 5,
    title: 'Welcome to the Godot Forum! :wave:',
    slug: 'welcome-to-the-godot-forum',
    posts_count: 293,
    reply_count: 292,
    highest_post_number: 293,
    image_url: null,
    created_at: '2023-08-01T12:00:00.000Z',
    last_posted_at: '2026-09-18T14:30:00.000Z',
    bumped: true,
    bumped_at: '2026-09-18T14:30:00.000Z',
    unseen: false,
    pinned: true,
    pinned_globally: true,
    visible: true,
    closed: false,
    archived: false,
    views: 27925,
    like_count: 1540,
    has_summary: true,
    archetype: 'regular',
    category_id: 4,
    tags: ['announcements', 'community'],
    excerpt: 'Welcome to the official Godot Engine forum! Please introduce yourself, read the community guidelines, and enjoy making games together!'
  },
  {
    id: 144358,
    title: 'Three professions, one town: what I learned building a life RPG solo in Godot 4.7',
    slug: 'three-professions-one-town-what-i-learned-building-a-life-rpg-solo-in-godot-4-7',
    posts_count: 20,
    reply_count: 19,
    highest_post_number: 20,
    image_url: 'https://forum.godotengine.org/uploads/default/original/2X/c/cbfa764bec13cc2f9506f1b9c9685e40766af7ba.png',
    created_at: '2026-09-19T08:12:00.000Z',
    last_posted_at: '2026-09-20T21:40:00.000Z',
    bumped: true,
    bumped_at: '2026-09-20T21:40:00.000Z',
    unseen: false,
    pinned: false,
    pinned_globally: false,
    visible: true,
    closed: false,
    archived: false,
    views: 230,
    like_count: 85,
    has_summary: true,
    archetype: 'regular',
    category_id: 24,
    tags: ['godot-4', 'gdscript', '3d', 'game'],
    excerpt: 'Hi everyone! Over the past 14 months I have been solo-developing a life simulation RPG set in an isolated mountain town. Here are the 5 architectural lessons I learned using Godot 4.'
  },
  {
    id: 144463,
    title: 'Godot MCP Studio, an AI tool for Godot 4',
    slug: 'godot-mcp-studio-an-ai-tool-for-godot-4',
    posts_count: 8,
    reply_count: 7,
    highest_post_number: 8,
    image_url: null,
    created_at: '2026-09-20T11:20:00.000Z',
    last_posted_at: '2026-09-20T22:15:00.000Z',
    bumped: true,
    bumped_at: '2026-09-20T22:15:00.000Z',
    unseen: false,
    pinned: false,
    pinned_globally: false,
    visible: true,
    closed: false,
    archived: false,
    views: 186,
    like_count: 42,
    has_summary: false,
    archetype: 'regular',
    category_id: 16,
    tags: ['godot-4', 'gdscript', 'tools', 'ai'],
    excerpt: 'I developed an MCP (Model Context Protocol) server and editor bridge that lets AI agents inspect scene tree hierarchies, run GDScript tests, and generate shader templates directly in Godot.'
  },
  {
    id: 144453,
    title: "Can't get time slowing to work.",
    slug: 'cant-get-time-slowing-to-work',
    posts_count: 6,
    reply_count: 5,
    highest_post_number: 6,
    image_url: null,
    created_at: '2026-09-20T09:30:00.000Z',
    last_posted_at: '2026-09-20T20:10:00.000Z',
    bumped: true,
    bumped_at: '2026-09-20T20:10:00.000Z',
    unseen: false,
    pinned: false,
    pinned_globally: false,
    visible: true,
    closed: false,
    archived: false,
    views: 94,
    like_count: 12,
    has_summary: false,
    archetype: 'regular',
    category_id: 7,
    tags: ['godot-4', 'gdscript'],
    excerpt: 'I am trying to implement a bullet-time effect using Engine.time_scale = 0.2, but my player input handling and tween animations feel completely broken. What is the recommended way?'
  },
  {
    id: 144452,
    title: 'How can I get the collision layer of a colliding tile in a TileMapLayer?',
    slug: 'how-can-i-get-the-collision-layer-of-a-colliding-tile-in-a-tilemaplayer',
    posts_count: 4,
    reply_count: 3,
    highest_post_number: 4,
    image_url: null,
    created_at: '2026-09-20T08:50:00.000Z',
    last_posted_at: '2026-09-20T18:05:00.000Z',
    bumped: true,
    bumped_at: '2026-09-20T18:05:00.000Z',
    unseen: false,
    pinned: false,
    pinned_globally: false,
    visible: true,
    closed: false,
    archived: false,
    views: 82,
    like_count: 9,
    has_summary: false,
    archetype: 'regular',
    category_id: 7,
    tags: ['godot-4', '2d', 'tilemap'],
    excerpt: 'In Godot 4.3+, TileMap is split into TileMapLayer. When a CharacterBody2D collides with a tile via move_and_slide(), how do I query which collision layer the tile specifically belongs to?'
  },
  {
    id: 144420,
    title: 'Shading with an animatedsprite 3d set to billboard',
    slug: 'shading-with-an-animatedsprite-3d-set-to-billboard',
    posts_count: 5,
    reply_count: 4,
    highest_post_number: 5,
    image_url: null,
    created_at: '2026-09-19T22:15:00.000Z',
    last_posted_at: '2026-09-20T16:30:00.000Z',
    bumped: true,
    bumped_at: '2026-09-20T16:30:00.000Z',
    unseen: false,
    pinned: false,
    pinned_globally: false,
    visible: true,
    closed: false,
    archived: false,
    views: 76,
    like_count: 14,
    has_summary: false,
    archetype: 'regular',
    category_id: 10,
    tags: ['godot-4', '3d', 'shaders'],
    excerpt: 'I am creating an HD-2D style game using AnimatedSprite3D billboard mode. When lights hit the sprite, the normal calculations look flat. How to write a custom shader that respects world normals?'
  },
  {
    id: 144433,
    title: 'My first game, Warrior of the Inquisition 0.1.4, is available for testing!',
    slug: 'my-first-game-warrior-of-the-inquisition-0-1-4-is-available-for-testing',
    posts_count: 6,
    reply_count: 5,
    highest_post_number: 6,
    image_url: null,
    created_at: '2026-09-20T04:10:00.000Z',
    last_posted_at: '2026-09-20T19:22:00.000Z',
    bumped: true,
    bumped_at: '2026-09-20T19:22:00.000Z',
    unseen: false,
    pinned: false,
    pinned_globally: false,
    visible: true,
    closed: false,
    archived: false,
    views: 120,
    like_count: 28,
    has_summary: false,
    archetype: 'regular',
    category_id: 15,
    tags: ['godot-4', '2d', 'game'],
    excerpt: 'After 6 months of learning Godot, I finally finished a playable demo of my dark fantasy action platformer. Would love feedback on movement weight and combat feedback!'
  },
  {
    id: 144465,
    title: 'Grab focus on buttons created during game',
    slug: 'grab-focus-on-buttons-created-during-game',
    posts_count: 3,
    reply_count: 2,
    highest_post_number: 3,
    image_url: null,
    created_at: '2026-09-20T12:00:00.000Z',
    last_posted_at: '2026-09-20T15:40:00.000Z',
    bumped: true,
    bumped_at: '2026-09-20T15:40:00.000Z',
    unseen: false,
    pinned: false,
    pinned_globally: false,
    visible: true,
    closed: false,
    archived: false,
    views: 45,
    like_count: 6,
    has_summary: false,
    archetype: 'regular',
    category_id: 8,
    tags: ['godot-4', 'gdscript', 'ui'],
    excerpt: 'When dynamically populating an inventory grid with Button nodes, calling grab_focus() immediately after add_child() does not seem to work on gamepads. What is the proper signal/order?'
  },
  {
    id: 144456,
    title: 'Modern Items Asset Pack (CC0)',
    slug: 'modern-items-asset-pack',
    posts_count: 4,
    reply_count: 3,
    highest_post_number: 4,
    image_url: null,
    created_at: '2026-09-20T10:15:00.000Z',
    last_posted_at: '2026-09-20T17:30:00.000Z',
    bumped: true,
    bumped_at: '2026-09-20T17:30:00.000Z',
    unseen: false,
    pinned: false,
    pinned_globally: false,
    visible: true,
    closed: false,
    archived: false,
    views: 112,
    like_count: 36,
    has_summary: false,
    archetype: 'regular',
    category_id: 25,
    tags: ['2d', 'assets'],
    excerpt: 'Here is a free 32x32 pixel art inventory pack featuring modern electronic gadgets, tools, and consumables. 100% free for commercial use under CC0.'
  }
]

export const MOCK_TOPIC_DETAILS: Record<number, DiscourseTopicDetail> = {
  144358: {
    id: 144358,
    title: 'Three professions, one town: what I learned building a life RPG solo in Godot 4.7',
    posts_count: 3,
    created_at: '2026-09-19T08:12:00.000Z',
    views: 230,
    reply_count: 2,
    like_count: 85,
    last_posted_at: '2026-09-20T21:40:00.000Z',
    visible: true,
    closed: false,
    archived: false,
    has_summary: true,
    archetype: 'regular',
    slug: 'three-professions-one-town-what-i-learned-building-a-life-rpg-solo-in-godot-4-7',
    category_id: 24,
    word_count: 650,
    user_id: 84001,
    tags: ['godot-4', 'gdscript', '3d', 'game'],
    post_stream: {
      stream: [1, 2, 3],
      posts: [
        {
          id: 101,
          name: 'Illtal Dev',
          username: 'illtal',
          avatar_template: 'https://avatars.githubusercontent.com/u/1024001?v=4',
          created_at: '2026-09-19T08:12:00.000Z',
          cooked: `
            <p>大家好！过去 14 个月里，我一直在独自开发一款以孤立山地小镇为背景的生活模拟 RPG。在历经无数次重构后，目前游戏已进入稳定开发期。我想与大家分享在 Godot 4.x 中独立开发复杂项目的 5 个核心经验：</p>
            <h3>1. 使用自定义 Resource 管理 NPC 数据</h3>
            <p>不要把 NPC 的职业逻辑全部塞到场景节点里。我创建了 <code>NPCData</code> 自定义资源，存储作息时间表、对话树引用与库存清单：</p>
            <pre><code class="language-gdscript">class_name NPCData extends Resource

@export var character_name: String
@export var profession: ProfessionType
@export var daily_schedule: Array[ScheduleEntry]
</code></pre>
            <h3>2. 复合场景（Composite Scenes）与可组合动画</h3>
            <p>角色外观支持自由更换服装。我使用单个 <code>AnimationPlayer</code> 驱动父骨骼，所有服装网格作为子节点共享骨骼变换，性能非常出色。</p>
            <h3>3. 事件总线（Event Bus）的设计边界</h3>
            <p>全局单例信号非常方便，但在中大型项目中容易造成追溯困难。建议仅在跨大系统（如天气变化、昼夜交替、保存系统）时使用全局 EventBus，而局部交互尽量使用明确的直接信号连接。</p>
            <p>欢迎交流讨论，有任何关于 3D 优化和数据架构的问题我都乐意解答！</p>
          `,
          post_number: 1,
          post_type: 1,
          updated_at: '2026-09-19T08:12:00.000Z',
          reply_count: 2,
          quote_count: 0,
          incoming_link_count: 0,
          reads: 210,
          readers_count: 210,
          score: 85,
          yours: false,
          topic_id: 144358,
          topic_slug: 'three-professions-one-town-what-i-learned-building-a-life-rpg-solo-in-godot-4-7',
          display_username: 'Illtal Dev',
          version: 1,
          can_edit: false,
          can_delete: false,
          can_recover: false,
          can_see_hidden_post: false,
          can_wiki: false,
          moderator: false,
          admin: false,
          staff: false,
          user_id: 84001,
          hidden: false,
          trust_level: 2,
          user_deleted: false,
          can_view_edit_history: false,
          wiki: false
        },
        {
          id: 102,
          name: 'Sword Studios',
          username: 'swordstudios',
          avatar_template: 'https://avatars.githubusercontent.com/u/1024002?v=4',
          created_at: '2026-09-19T14:30:00.000Z',
          cooked: `
            <p>非常赞同关于 Resource 的建议！我们在做装备系统时也是全面转向了自定义 Resource，不仅能够直接在检查器（Inspector）中编辑，还可以很方便地用 <code>ResourceSaver</code> 和 <code>ResourceLoader</code> 序列化为磁盘文件，比起手写 JSON 健壮太多了！</p>
            <p>顺便想请教一下：你的小镇寻路使用的是单个大 NavMesh 还是分块动态生成的？</p>
          `,
          post_number: 2,
          post_type: 1,
          updated_at: '2026-09-19T14:30:00.000Z',
          reply_count: 1,
          quote_count: 0,
          incoming_link_count: 0,
          reads: 180,
          readers_count: 180,
          score: 30,
          yours: false,
          topic_id: 144358,
          topic_slug: 'three-professions-one-town-what-i-learned-building-a-life-rpg-solo-in-godot-4-7',
          display_username: 'Sword Studios',
          version: 1,
          can_edit: false,
          can_delete: false,
          can_recover: false,
          can_see_hidden_post: false,
          can_wiki: false,
          moderator: false,
          admin: false,
          staff: false,
          user_id: 84002,
          hidden: false,
          trust_level: 3,
          user_deleted: false,
          can_view_edit_history: false,
          wiki: false
        },
        {
          id: 103,
          name: 'Illtal Dev',
          username: 'illtal',
          avatar_template: 'https://avatars.githubusercontent.com/u/1024001?v=4',
          created_at: '2026-09-20T21:40:00.000Z',
          cooked: `
            <p>@swordstudios 小镇区域使用的是静态烘焙的整体 <code>NavigationRegion3D</code>，而在玩家建造农场设施时，会使用 <code>NavigationObstacle3D</code> 动态改变避障路线，这样兼顾了烘焙性能与动态修改能力。</p>
          `,
          post_number: 3,
          post_type: 1,
          updated_at: '2026-09-20T21:40:00.000Z',
          reply_count: 0,
          quote_count: 0,
          incoming_link_count: 0,
          reads: 140,
          readers_count: 140,
          score: 25,
          yours: false,
          topic_id: 144358,
          topic_slug: 'three-professions-one-town-what-i-learned-building-a-life-rpg-solo-in-godot-4-7',
          display_username: 'Illtal Dev',
          version: 1,
          can_edit: false,
          can_delete: false,
          can_recover: false,
          can_see_hidden_post: false,
          can_wiki: false,
          moderator: false,
          admin: false,
          staff: false,
          user_id: 84001,
          hidden: false,
          trust_level: 2,
          user_deleted: false,
          can_view_edit_history: false,
          wiki: false
        }
      ]
    }
  }
}
